/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jarkom;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/** 
 *
 * @author rinda
 */
public class FormSupplierCategory extends javax.swing.JFrame {
private Connections conn = new Connections();

private DefaultTableModel model;
    private Object tblcategory;

private void autonumber(){
    try{
        Connection c = Connections.getConnections();
        Statement s = c.createStatement();
        String sql = "SELECT * FROM Supplier_Category ORDER BY " + "id_SCategory DESC";
        ResultSet r = s.executeQuery(sql);
        if(r.next()){
            String CategoryCode = r.getString("SCategory_Code").substring(2);
            String CS = ""+ (Integer.parseInt("Category_code")+1);
            String Zero = "";
            if(CS.length()== 1){
                Zero = "00";
            }else if (CS.length()==2){
                Zero= "0";
            }else{
                Zero="";
            }
            txtCategoryCode.setText("CS"+Zero+CS);
        }else{ txtCategoryCode.setText("CS001");
        }
        r.close();
        s.close();
    }catch(Exception e){
        System.out.println("Auto Number Eror");
    }
}
private void clear(){
    txtCategoryName.setText("");
}

public void loadData(){
    model.getDataVector().removeAllElements();
    model.fireTableDataChanged();
    try{
        Connection c = Connections.getConnections();
        Statement s = c.createStatement();
        
        String sql = "SELECT * FROM supplier_category";
        ResultSet r = s.executeQuery(sql);
        
        while(r.next()){
            Object[] o = new Object[3];
            o [0] = r.getString("id_SCategory");
            o [1] = r.getString("SCategory_Code");
            o [2] = r.getString("SCategory_nama");
            model.addRow(o);
        }
        r.close();
        s.close();
    }catch(SQLException e){
        System.out.println("Something wrong");
                    
        }
}
    /**
     * Creates new form FromSupplierCategory
     */
    public FormSupplierCategory() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtCategoryCode.setEnabled(False);
        model = new DefaultTableModel();
        tblCategory.setModel(model);
        model.addColumn("ID");
        model.addColumn("Category Code");
        model.addColumn("Category Name");
        
        loadData();
        autonumber();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCategoryCode = new javax.swing.JTextField();
        txtCategoryName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategory = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCategoryCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryCodeActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Category Supplier");

        jLabel2.setText("Category Code");

        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Category Code", "Category Name"
            }
        ));
        tblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategory);

        jLabel3.setText("Category Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCategoryCode, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCategoryCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCategoryCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryCodeActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int i = tblcategory.getSelectedRow();
        if (i == -1){
            return;
        } 
         String id = (String)model.getValueAt(i, 0);
        String CategoryCode = txtCategoryCode.getText();
        String CategoryName = txtCategoryName.getText();
        try{
            Connection c = Connections.getConnection();
            String sql = "UPDATE supplier_Category SET SCategory_code =,Scategory_name =? " + "WHERE id_SCategory";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(2, CategoryCode);
            p.setString(2, CategoryName);
            p.setString(3, id);
            p.close();
             JOptionPane.showMessageDialog(null,"The data has been update");
        }catch(SQLException e){
            System.out.println("Update Error");
        }finally{
            loadData();
            autonumber();
            clear();           
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int i = tblcategory.getSelectedRow();
        if(i == -1){
            return;
        } 
        String id = (String)model.getValueAt(i, 0);
        int question = JOptionPane.showConfirmDialog(null,
                "Sure this data will be delet?",
                "Confrim",JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE); 
        if(question == JOptionPane.OK_OPTION){
            try{
                Connection c = Connections.getConnections();
                String sql = "DELETE FROM product_category WHERE id_PCategory = ?";
                try (PreparedStatement p = c.prepareStatement(sql)) {
                    p.setString(1, id);
                    p.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "The data been deleted");
            }catch(SQLException e){
                System.out.println("Delete Eror");
            }finally{
                loadData();
                autonumber();
                btnSave.setEnabled(true);
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
                String CategoryCode = txtCategoryCode.getText();
        String CategoryName = txtCategoryName.getText();
        try{
            Connection c = Connections.getConnections();
            String sql = "SELECT * FROM supplier_category(SCategory_code,"
                    + "SCategory_nama) VALUES (?,?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, CategoryCode);
            p.setString(2, CategoryName);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null,"Data Successful Saved");
        }catch(SQLException e){
            System.out.println("Something wrong");
        }finally{
            loadData();
            autonumber();
            clear();            
        } 
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        clear();
        loadData();
        btnSave.setEnabled(true);
        autonumber();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoryMouseClicked
        // TODO add your handling code here:
        btnSave.setEnabled(false);
        int i = tblcategory.getSelectedRow();
        if(i == -1){
            return;
        }
        String CategoryCode = (String)model.getValueAt(i, 1);
        txtCategoryCode.setText(CategoryCode);
        String CategoryName = (String)model.getValueAt(i, 2);
        txtCategoryName.setText(CategoryName);
    }//GEN-LAST:event_tblCategoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSupplierCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSupplierCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSupplierCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSupplierCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSupplierCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCategory;
    private javax.swing.JTextField txtCategoryCode;
    private javax.swing.JTextField txtCategoryName;
    // End of variables declaration//GEN-END:variables
}
